# Generated by Django 4.2 on 2025-09-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HrAttendance',
            fields=[
                ('attendance_id', models.BigAutoField(db_column='Attendance_ID', primary_key=True, serialize=False)),
                ('attendance_date', models.DateField(db_column='Attendance_Date')),
                ('clock_in', models.TimeField(blank=True, db_column='Clock_In', null=True)),
                ('clock_out', models.TimeField(blank=True, db_column='Clock_Out', null=True)),
                ('shift_code', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Shift_Code', max_length=20, null=True)),
                ('work_hours', models.IntegerField(blank=True, db_column='Work_Hours', null=True)),
                ('overtime_hours', models.IntegerField(blank=True, db_column='Overtime_Hours', null=True)),
                ('late_minutes', models.IntegerField(blank=True, db_column='Late_Minutes', null=True)),
                ('early_minutes', models.IntegerField(blank=True, db_column='Early_Minutes', null=True)),
                ('status', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Status', max_length=20, null=True)),
                ('machine_ip', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Machine_IP', max_length=20, null=True)),
                ('created_by', models.IntegerField(db_column='Created_By')),
                ('created_date', models.DateTimeField(db_column='Created_Date')),
                ('modified_by', models.IntegerField(blank=True, db_column='Modified_By', null=True)),
                ('modified_date', models.DateTimeField(blank=True, db_column='Modified_Date', null=True)),
            ],
            options={
                'db_table': 'HR_Attendance',
                'managed': False,
            },
        ),
    ]
