# Generated by Django 4.2 on 2025-09-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityUsers',
            fields=[
                ('user_id', models.AutoField(db_column='User_ID', primary_key=True, serialize=False)),
                ('user_name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='User_Name', max_length=50, unique=True)),
                ('full_name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Full_Name', max_length=100)),
                ('password_hash', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Password_Hash', max_length=64)),
                ('is_active', models.BooleanField(db_column='Is_Active')),
                ('created_date', models.DateTimeField(db_column='Created_Date')),
            ],
            options={
                'db_table': 'Security_Users',
                'managed': False,
            },
        ),
    ]
