# Generated by Django 4.2 on 2025-09-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HrEmpNote',
            fields=[
                ('note_id', models.BigAutoField(db_column='Note_ID', primary_key=True, serialize=False)),
                ('note_date', models.DateTimeField(db_column='Note_Date')),
                ('subject', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Subject', max_length=200)),
                ('details', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Details', max_length=1000, null=True)),
                ('severity', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Severity', max_length=20, null=True)),
                ('created_by', models.IntegerField(db_column='Created_By')),
                ('created_date', models.DateTimeField(db_column='Created_Date')),
                ('modified_by', models.IntegerField(blank=True, db_column='Modified_By', null=True)),
                ('modified_date', models.DateTimeField(blank=True, db_column='Modified_Date', null=True)),
            ],
            options={
                'db_table': 'HR_Emp_Note',
                'managed': False,
            },
        ),
    ]
