# Generated by Django 4.2 on 2025-09-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HrSocialInsurance',
            fields=[
                ('si_id', models.BigAutoField(db_column='SI_ID', primary_key=True, serialize=False)),
                ('insurance_no', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Insurance_No', max_length=30, null=True, unique=True)),
                ('form_s1_received', models.BooleanField(db_column='Form_S1_Received')),
                ('form_s1_date', models.DateField(blank=True, db_column='Form_S1_Date', null=True)),
                ('form_s6_received', models.BooleanField(db_column='Form_S6_Received')),
                ('form_s6_date', models.DateField(blank=True, db_column='Form_S6_Date', null=True)),
                ('subscription_date', models.DateField(blank=True, db_column='Subscription_Date', null=True)),
                ('subscription_salary', models.DecimalField(blank=True, db_column='Subscription_Salary', decimal_places=2, max_digits=18, null=True)),
                ('employee_percent', models.DecimalField(blank=True, db_column='Employee_Percent', decimal_places=2, max_digits=5, null=True)),
                ('company_percent', models.DecimalField(blank=True, db_column='Company_Percent', decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Status', max_length=20, null=True)),
                ('exit_date', models.DateField(blank=True, db_column='Exit_Date', null=True)),
                ('exit_reason', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Exit_Reason', max_length=100, null=True)),
                ('created_by', models.IntegerField(db_column='Created_By')),
                ('created_date', models.DateTimeField(db_column='Created_Date')),
                ('modified_by', models.IntegerField(blank=True, db_column='Modified_By', null=True)),
                ('modified_date', models.DateTimeField(blank=True, db_column='Modified_Date', null=True)),
            ],
            options={
                'db_table': 'HR_Social_Insurance',
                'managed': False,
            },
        ),
    ]
