# Generated by Django 4.2 on 2025-09-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SetupCompany',
            fields=[
                ('company_id', models.AutoField(db_column='Company_ID', primary_key=True, serialize=False)),
                ('company_code', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Company_Code', max_length=10, unique=True)),
                ('company_name_ar', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Company_Name_AR', max_length=100)),
                ('company_name_en', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Company_Name_EN', max_length=100, null=True)),
                ('commercial_record', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Commercial_Record', max_length=50, null=True)),
                ('tax_number', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Tax_Number', max_length=30, null=True)),
                ('phone1', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Phone1', max_length=20, null=True)),
                ('phone2', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Phone2', max_length=20, null=True)),
                ('email', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Email', max_length=100, null=True)),
                ('website', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Website', max_length=100, null=True)),
                ('country', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Country', max_length=50, null=True)),
                ('governorate', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Governorate', max_length=50, null=True)),
                ('city', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='City', max_length=50, null=True)),
                ('district', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='District', max_length=50, null=True)),
                ('street', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Street', max_length=100, null=True)),
                ('building_no', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Building_No', max_length=20, null=True)),
                ('logo', models.BinaryField(blank=True, db_column='Logo', null=True)),
                ('is_active', models.BooleanField(db_column='Is_Active')),
                ('created_by', models.IntegerField(db_column='Created_By')),
                ('created_date', models.DateTimeField(db_column='Created_Date')),
                ('modified_by', models.IntegerField(blank=True, db_column='Modified_By', null=True)),
                ('modified_date', models.DateTimeField(blank=True, db_column='Modified_Date', null=True)),
            ],
            options={
                'db_table': 'Setup_Company',
                'managed': False,
            },
        ),
    ]
