# Generated by Django 4.2 on 2025-09-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HrEmpLeaveBalance',
            fields=[
                ('balance_id', models.AutoField(db_column='Balance_ID', primary_key=True, serialize=False)),
                ('year', models.IntegerField(db_column='Year')),
                ('opening_balance', models.IntegerField(db_column='Opening_Balance')),
                ('consumed_days', models.IntegerField(db_column='Consumed_Days')),
                ('remaining_balance', models.IntegerField(blank=True, db_column='Remaining_Balance', null=True)),
                ('carry_forward_days', models.IntegerField(db_column='Carry_Forward_Days')),
                ('created_by', models.IntegerField(db_column='Created_By')),
                ('created_date', models.DateTimeField(db_column='Created_Date')),
                ('modified_by', models.IntegerField(blank=True, db_column='Modified_By', null=True)),
                ('modified_date', models.DateTimeField(blank=True, db_column='Modified_Date', null=True)),
            ],
            options={
                'db_table': 'HR_Emp_Leave_Balance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HrEmpLeaveRequest',
            fields=[
                ('leave_request_id', models.AutoField(db_column='Leave_Request_ID', primary_key=True, serialize=False)),
                ('start_date', models.DateField(db_column='Start_Date')),
                ('end_date', models.DateField(db_column='End_Date')),
                ('days_count', models.IntegerField(db_column='Days_Count')),
                ('reason', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Reason', max_length=500, null=True)),
                ('contact_phone', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Contact_Phone', max_length=20, null=True)),
                ('contact_address', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Contact_Address', max_length=200, null=True)),
                ('status', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Status', max_length=20, null=True)),
                ('approved_date', models.DateTimeField(blank=True, db_column='Approved_Date', null=True)),
                ('rejection_reason', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Rejection_Reason', max_length=500, null=True)),
                ('created_by', models.IntegerField(db_column='Created_By')),
                ('created_date', models.DateTimeField(db_column='Created_Date')),
                ('modified_by', models.IntegerField(blank=True, db_column='Modified_By', null=True)),
                ('modified_date', models.DateTimeField(blank=True, db_column='Modified_Date', null=True)),
            ],
            options={
                'db_table': 'HR_Emp_Leave_Request',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SetupHoliday',
            fields=[
                ('holiday_id', models.AutoField(db_column='Holiday_ID', primary_key=True, serialize=False)),
                ('holiday_date', models.DateField(db_column='Holiday_Date')),
                ('holiday_name_ar', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Holiday_Name_AR', max_length=100)),
                ('holiday_name_en', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Holiday_Name_EN', max_length=100, null=True)),
                ('is_recurring', models.BooleanField(db_column='Is_Recurring')),
                ('created_by', models.IntegerField(db_column='Created_By')),
                ('created_date', models.DateTimeField(db_column='Created_Date')),
            ],
            options={
                'db_table': 'Setup_Holiday',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SetupLeaveType',
            fields=[
                ('leave_type_id', models.AutoField(db_column='Leave_Type_ID', primary_key=True, serialize=False)),
                ('leave_code', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Leave_Code', max_length=20)),
                ('leave_name_ar', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Leave_Name_AR', max_length=100)),
                ('leave_name_en', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Leave_Name_EN', max_length=100, null=True)),
                ('paid_unpaid', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Paid_Unpaid', max_length=1, null=True)),
                ('max_days_year', models.IntegerField(db_column='Max_Days_Year')),
                ('carry_forward', models.BooleanField(db_column='Carry_Forward')),
                ('max_carry', models.IntegerField(blank=True, db_column='Max_Carry', null=True)),
                ('gender_limit', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Gender_Limit', max_length=1, null=True)),
                ('is_active', models.BooleanField(db_column='Is_Active')),
                ('created_by', models.IntegerField(db_column='Created_By')),
                ('created_date', models.DateTimeField(db_column='Created_Date')),
                ('modified_by', models.IntegerField(blank=True, db_column='Modified_By', null=True)),
                ('modified_date', models.DateTimeField(blank=True, db_column='Modified_Date', null=True)),
            ],
            options={
                'db_table': 'Setup_Leave_Type',
                'managed': False,
            },
        ),
    ]
