# Generated by Django 4.2 on 2025-09-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollHeader',
            fields=[
                ('payroll_id', models.BigAutoField(db_column='Payroll_ID', primary_key=True, serialize=False)),
                ('payroll_month', models.DateField(db_column='Payroll_Month')),
                ('status', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Status', max_length=20, null=True)),
                ('processed_date', models.DateTimeField(blank=True, db_column='Processed_Date', null=True)),
                ('processed_by', models.IntegerField(blank=True, db_column='Processed_By', null=True)),
                ('notes', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Notes', max_length=500, null=True)),
                ('created_by', models.IntegerField(db_column='Created_By')),
                ('created_date', models.DateTimeField(db_column='Created_Date')),
                ('modified_by', models.IntegerField(blank=True, db_column='Modified_By', null=True)),
                ('modified_date', models.DateTimeField(blank=True, db_column='Modified_Date', null=True)),
            ],
            options={
                'db_table': 'Payroll_Header',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PayrollLine',
            fields=[
                ('line_id', models.BigAutoField(db_column='Line_ID', primary_key=True, serialize=False)),
                ('amount', models.DecimalField(db_column='Amount', decimal_places=2, max_digits=18)),
                ('notes', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Notes', max_length=200, null=True)),
                ('created_by', models.IntegerField(db_column='Created_By')),
                ('created_date', models.DateTimeField(db_column='Created_Date')),
                ('modified_by', models.IntegerField(blank=True, db_column='Modified_By', null=True)),
                ('modified_date', models.DateTimeField(blank=True, db_column='Modified_Date', null=True)),
            ],
            options={
                'db_table': 'Payroll_Line',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SetupPayrollItem',
            fields=[
                ('item_id', models.AutoField(db_column='Item_ID', primary_key=True, serialize=False)),
                ('item_code', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Item_Code', max_length=20)),
                ('item_name_ar', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Item_Name_AR', max_length=100)),
                ('item_name_en', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Item_Name_EN', max_length=100, null=True)),
                ('item_type', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Item_Type', max_length=1, null=True)),
                ('calculation_type', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Calculation_Type', max_length=30, null=True)),
                ('default_value', models.DecimalField(blank=True, db_column='Default_Value', decimal_places=2, max_digits=18, null=True)),
                ('taxable', models.BooleanField(db_column='Taxable')),
                ('insurable', models.BooleanField(db_column='Insurable')),
                ('is_active', models.BooleanField(db_column='Is_Active')),
                ('created_by', models.IntegerField(db_column='Created_By')),
                ('created_date', models.DateTimeField(db_column='Created_Date')),
                ('modified_by', models.IntegerField(blank=True, db_column='Modified_By', null=True)),
                ('modified_date', models.DateTimeField(blank=True, db_column='Modified_Date', null=True)),
            ],
            options={
                'db_table': 'Setup_Payroll_Item',
                'managed': False,
            },
        ),
    ]
