# Generated by Django 4.2 on 2025-09-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HrTermination',
            fields=[
                ('termination_id', models.BigAutoField(db_column='Termination_ID', primary_key=True, serialize=False)),
                ('request_date', models.DateField(db_column='Request_Date')),
                ('last_working_date', models.DateField(db_column='Last_Working_Date')),
                ('reason_type', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Reason_Type', max_length=30, null=True)),
                ('reason_details', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Reason_Details', max_length=500, null=True)),
                ('notice_period_days', models.IntegerField(blank=True, db_column='Notice_Period_Days', null=True)),
                ('notice_end_date', models.DateField(blank=True, db_column='Notice_End_Date', null=True)),
                ('settlement_amount', models.DecimalField(blank=True, db_column='Settlement_Amount', decimal_places=2, max_digits=18, null=True)),
                ('settlement_paid', models.BooleanField(db_column='Settlement_Paid')),
                ('created_by', models.IntegerField(db_column='Created_By')),
                ('created_date', models.DateTimeField(db_column='Created_Date')),
                ('modified_by', models.IntegerField(blank=True, db_column='Modified_By', null=True)),
                ('modified_date', models.DateTimeField(blank=True, db_column='Modified_Date', null=True)),
            ],
            options={
                'db_table': 'HR_Termination',
                'managed': False,
            },
        ),
    ]
