# Generated by Django 4.2 on 2025-09-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HrHealthInsurance',
            fields=[
                ('hi_id', models.BigAutoField(db_column='HI_ID', primary_key=True, serialize=False)),
                ('provider', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Provider', max_length=100, null=True)),
                ('policy_no', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Policy_No', max_length=30, null=True)),
                ('card_no', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Card_No', max_length=30, null=True)),
                ('start_date', models.DateField(blank=True, db_column='Start_Date', null=True)),
                ('end_date', models.DateField(blank=True, db_column='End_Date', null=True)),
                ('insurance_job_code', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Insurance_Job_Code', max_length=20, null=True)),
                ('insurance_job_name', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Insurance_Job_Name', max_length=100, null=True)),
                ('premium_amount', models.DecimalField(blank=True, db_column='Premium_Amount', decimal_places=2, max_digits=18, null=True)),
                ('notes', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Notes', max_length=200, null=True)),
                ('created_by', models.IntegerField(db_column='Created_By')),
                ('created_date', models.DateTimeField(db_column='Created_Date')),
                ('modified_by', models.IntegerField(blank=True, db_column='Modified_By', null=True)),
                ('modified_date', models.DateTimeField(blank=True, db_column='Modified_Date', null=True)),
            ],
            options={
                'db_table': 'HR_Health_Insurance',
                'managed': False,
            },
        ),
    ]
