# Generated by Django 4.2 on 2025-09-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HrEmpTransport',
            fields=[
                ('transport_id', models.AutoField(db_column='Transport_ID', primary_key=True, serialize=False)),
                ('car_plate', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Car_Plate', max_length=20, null=True)),
                ('car_model', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Car_Model', max_length=50, null=True)),
                ('pickup_point', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Pickup_Point', max_length=200, null=True)),
                ('pickup_time', models.TimeField(blank=True, db_column='Pickup_Time', null=True)),
                ('drop_time', models.TimeField(blank=True, db_column='Drop_Time', null=True)),
                ('driver_name', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Driver_Name', max_length=100, null=True)),
                ('is_active', models.BooleanField(db_column='Is_Active')),
                ('created_by', models.IntegerField(db_column='Created_By')),
                ('created_date', models.DateTimeField(db_column='Created_Date')),
                ('modified_by', models.IntegerField(blank=True, db_column='Modified_By', null=True)),
                ('modified_date', models.DateTimeField(blank=True, db_column='Modified_Date', null=True)),
            ],
            options={
                'db_table': 'HR_Emp_Transport',
                'managed': False,
            },
        ),
    ]
