# Generated by Django 4.2 on 2025-09-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SetupDocumentType',
            fields=[
                ('doc_type_id', models.AutoField(db_column='Doc_Type_ID', primary_key=True, serialize=False)),
                ('doc_code', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Doc_Code', max_length=20)),
                ('doc_name_ar', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Doc_Name_AR', max_length=100)),
                ('doc_name_en', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Doc_Name_EN', max_length=100, null=True)),
                ('is_mandatory', models.BooleanField(db_column='Is_Mandatory')),
                ('expiry_alert_days', models.IntegerField(blank=True, db_column='Expiry_Alert_Days', null=True)),
                ('is_active', models.BooleanField(db_column='Is_Active')),
                ('created_by', models.IntegerField(db_column='Created_By')),
                ('created_date', models.DateTimeField(db_column='Created_Date')),
                ('modified_by', models.IntegerField(blank=True, db_column='Modified_By', null=True)),
                ('modified_date', models.DateTimeField(blank=True, db_column='Modified_Date', null=True)),
            ],
            options={
                'db_table': 'Setup_Document_Type',
                'managed': False,
            },
        ),
    ]
