# Generated by Django 4.2 on 2025-09-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HrEmpLoan',
            fields=[
                ('loan_id', models.AutoField(db_column='Loan_ID', primary_key=True, serialize=False)),
                ('request_date', models.DateField(db_column='Request_Date')),
                ('amount', models.DecimalField(db_column='Amount', decimal_places=2, max_digits=18)),
                ('installment_count', models.IntegerField(db_column='Installment_Count')),
                ('interest_rate', models.DecimalField(blank=True, db_column='Interest_Rate', decimal_places=2, max_digits=5, null=True)),
                ('monthly_amount', models.DecimalField(blank=True, db_column='Monthly_Amount', decimal_places=13, max_digits=29, null=True)),
                ('status', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Status', max_length=20, null=True)),
                ('approved_date', models.DateTimeField(blank=True, db_column='Approved_Date', null=True)),
                ('first_deduct_date', models.DateField(blank=True, db_column='First_Deduct_Date', null=True)),
                ('created_by', models.IntegerField(db_column='Created_By')),
                ('created_date', models.DateTimeField(db_column='Created_Date')),
                ('modified_by', models.IntegerField(blank=True, db_column='Modified_By', null=True)),
                ('modified_date', models.DateTimeField(blank=True, db_column='Modified_Date', null=True)),
            ],
            options={
                'db_table': 'HR_Emp_Loan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SetupLoanDeductionType',
            fields=[
                ('type_id', models.AutoField(db_column='Type_ID', primary_key=True, serialize=False)),
                ('type_code', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Type_Code', max_length=20)),
                ('type_name_ar', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Type_Name_AR', max_length=100)),
                ('type_name_en', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Type_Name_EN', max_length=100, null=True)),
                ('is_loan', models.BooleanField(db_column='Is_Loan')),
                ('max_amount', models.DecimalField(blank=True, db_column='Max_Amount', decimal_places=2, max_digits=18, null=True)),
                ('max_installment', models.IntegerField(blank=True, db_column='Max_Installment', null=True)),
                ('interest_rate', models.DecimalField(blank=True, db_column='Interest_Rate', decimal_places=2, max_digits=5, null=True)),
                ('is_active', models.BooleanField(db_column='Is_Active')),
                ('created_by', models.IntegerField(db_column='Created_By')),
                ('created_date', models.DateTimeField(db_column='Created_Date')),
                ('modified_by', models.IntegerField(blank=True, db_column='Modified_By', null=True)),
                ('modified_date', models.DateTimeField(blank=True, db_column='Modified_Date', null=True)),
            ],
            options={
                'db_table': 'Setup_Loan_Deduction_Type',
                'managed': False,
            },
        ),
    ]
