# Generated by Django 4.2 on 2025-09-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SetupDepartment',
            fields=[
                ('dept_id', models.AutoField(db_column='Dept_ID', primary_key=True, serialize=False)),
                ('dept_code', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Dept_Code', max_length=20)),
                ('dept_name_ar', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Dept_Name_AR', max_length=100)),
                ('dept_name_en', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Dept_Name_EN', max_length=100, null=True)),
                ('manager_emp_id', models.IntegerField(blank=True, db_column='Manager_Emp_ID', null=True)),
                ('is_active', models.BooleanField(db_column='Is_Active')),
                ('created_by', models.IntegerField(db_column='Created_By')),
                ('created_date', models.DateTimeField(db_column='Created_Date')),
                ('modified_by', models.IntegerField(blank=True, db_column='Modified_By', null=True)),
                ('modified_date', models.DateTimeField(blank=True, db_column='Modified_Date', null=True)),
            ],
            options={
                'db_table': 'Setup_Department',
                'managed': False,
            },
        ),
    ]
