# Generated by Django 4.2 on 2025-09-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HrEmpViolation',
            fields=[
                ('emp_violation_id', models.BigAutoField(db_column='Emp_Violation_ID', primary_key=True, serialize=False)),
                ('violation_date', models.DateField(db_column='Violation_Date')),
                ('details', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Details', max_length=500, null=True)),
                ('penalty_executed', models.BooleanField(db_column='Penalty_Executed')),
                ('executed_date', models.DateTimeField(blank=True, db_column='Executed_Date', null=True)),
                ('created_by', models.IntegerField(db_column='Created_By')),
                ('created_date', models.DateTimeField(db_column='Created_Date')),
                ('modified_by', models.IntegerField(blank=True, db_column='Modified_By', null=True)),
                ('modified_date', models.DateTimeField(blank=True, db_column='Modified_Date', null=True)),
            ],
            options={
                'db_table': 'HR_Emp_Violation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SetupViolationType',
            fields=[
                ('violation_id', models.AutoField(db_column='Violation_ID', primary_key=True, serialize=False)),
                ('violation_code', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Violation_Code', max_length=20)),
                ('violation_name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Violation_Name', max_length=100)),
                ('penalty_type', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Penalty_Type', max_length=30, null=True)),
                ('penalty_days', models.IntegerField(blank=True, db_column='Penalty_Days', null=True)),
                ('penalty_amount', models.DecimalField(blank=True, db_column='Penalty_Amount', decimal_places=2, max_digits=18, null=True)),
                ('is_active', models.BooleanField(db_column='Is_Active')),
                ('created_by', models.IntegerField(db_column='Created_By')),
                ('created_date', models.DateTimeField(db_column='Created_Date')),
                ('modified_by', models.IntegerField(blank=True, db_column='Modified_By', null=True)),
                ('modified_date', models.DateTimeField(blank=True, db_column='Modified_Date', null=True)),
            ],
            options={
                'db_table': 'Setup_Violation_Type',
                'managed': False,
            },
        ),
    ]
